### ISSUE TITLE
Tried to use GraphNotifier after `dispose` was called

### ISSUE THREAD

**Issue by ArneSaknussemm89** [flutterdata/flutter_data#105]
Having a strange error being thrown when I navigate between my screens. The error:
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following ProviderException was thrown building OnboardingBranchSelectionPage(dirty, dependencies: [UncontrolledProviderScope]):
An exception was thrown while building AutoDisposeProvider<List<Branch>>#00012().

Thrown exception:
An exception was thrown while building AutoDisposeStateNotifierProvider<DataStateNotifier<List<Branch>>, DataState<List<Branch>>>#00013(from: Instance of 'AutoDisposeStateNotifierProviderFamily<DataStateNotifier<List<Branch>>, DataState<List<Branch>>, WatchArgs<Branch>>', argument: WatchArgs<Branch>(null, false, null, null)).

Thrown exception:
An exception was thrown while building _AutoDisposeNotifierProvider<DataStateNotifier<List<Branch>>>#00014(from: Instance of '_AutoDisposeNotifierFamily<DataStateNotifier<List<Branch>>, WatchArgs<Branch>>', argument: WatchArgs<Branch>(null, false, null, null)).

Thrown exception:
Bad state: Tried to use GraphNotifier after `dispose` was called.

Consider checking `mounted`.
2

Stack trace:
#0      StateNotifier._debugIsMounted.<anonymous closure>
package:state_notifier/state_notifier.dart:128
#1      StateNotifier._debugIsMounted
package:state_notifier/state_notifier.dart:135
#2      StateNotifier.addListener
package:state_notifier/state_notifier.dart:226
#3      DelayedStateNotifier.addListener
package:flutter_data/…/graph/notifier_extension.dart:23
#4      _FunctionalStateNotifier.throttle
package:flutter_data/…/graph/notifier_extension.dart:62
#5      StateNotifierX.throttle
package:flutter_data/…/graph/notifier_extension.dart:129
#6      _RemoteAdapterWatch.throttledGraph
package:flutter_data/…/repository/remote_adapter_watch.dart:12
#7      _RemoteAdapterWatch.watchAll
package:flutter_data/…/repository/remote_adapter_watch.dart:70
#8      Repository.watchAll
package:flutter_data/…/repository/repository.dart:200
#9      _watchBranches.<anonymous closure>
package:grow_a_reader/models/models.g.dart:241
#10     _AutoDisposeNotifierFamily.create.<anonymous closure>
package:riverpod/…/state_notifier_provider/auto_dispose.dart:125
#11     new _AutoDisposeNotifierProvider.<anonymous closure>
package:riverpod/…/state_notifier_provider/auto_dispose.dart:10
#12     AutoDisposeProvider.create
package:riverpod/…/provider/auto_dispose.dart:16
#13     ProviderElement._runStateCreate
package:riverpod/…/framework/base_provider.dart:854
#14     ProviderElement.mount
package:riverpod/…/framework/base_provider.dart:775
#15     ProviderContainer.readProviderElement.<anonymous closure>
package:riverpod/…/framework/container.dart:335
#16     _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
#17     ProviderContainer.readProviderElement
package:riverpod/…/framework/container.dart:314
#18     ProviderElement.watch
package:riverpod/…/framework/base_provider.dart:555
#19     AutoDisposeStateNotifierProvider.create
package:riverpod/…/state_notifier_provider/auto_dispose.dart:56
#20     ProviderElement._runStateCreate
package:riverpod/…/framework/base_provider.dart:854
#21     ProviderElement.mount
package:riverpod/…/framework/base_provider.dart:775
#22     ProviderContainer.readProviderElement.<anonymous closure>
package:riverpod/…/framework/container.dart:335
#23     _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:140:29)
#24     ProviderContainer.readProviderElement
package:riverpod/…/framework/container.dart:314
#25     ProviderElement.watch
package:riverpod/…/framework/base_provider.dart:555
#26     Branch.provider.<anonymous closure>
package:grow_a_reader/models/branch.dart:20
```

Here is where the provider is:
```dart
class Branch extends DataModel<Branch> with ViewableTeaser {
  Branch({this.id, this.guid, this.name = ''});

  @override
  final int? id;

  String? guid;
  String name;

  @override
  Widget ViewTeaser() {
    return Text(name);
  }

  static final provider = Provider.autoDispose<List<Branch>>((ref) {
    final state = ref.watch(branchesProvider);

    if (state.model.isEmpty) return sampleBranches; // for testing
    return state.model;
  });
}

final branchesProvider = watchBranches(remote: false);
```

 And then to use the provider I'm using `hooks_riverpod` package and using `useProvider` inside a HookWidget.
```dart
@override
Widget build(BuildContext context) {
  final branches = useProvider(Branch.provider);
  /// etc etc rest of the widget displaying data
}
```

But if I navigate away from this screen, and then navigate back, that error is thrown. Tried going down the rabbit hole, but all I could tell was somehow the underlying Hive box that backs those models is being closed, but when that provider is accessed again it's not reopening the box (like I would expect)

**Comment by frank06** [comment]
Thanks for the detailed report! Will have a look at it

**Comment by ArneSaknussemm89** [comment]
Oh and I am also using `auto_route: '^2.2.0'` so maybe it's an issue between them? I can provide a `pubspec.lock` if you think that would be helpful.

**Comment by frank06** [comment]
No worries, this is an internal issue which I was able to reproduce in a test – a great first step. 

It has to do with a `StateNotifier` being disposed and then attempted to be used again. Strange as these are being used in tons of places in different apps. I guess we were lucky!

The fix is not totally obvious as there's a notifier rabbit hole happening and I don't want to remove a `dispose` that will result in memory leaks. I will continue later.

If you need a workaround, try commenting lines 89 and 241 in `lib/src/repository/remote_adapter_watch.dart` and you should stop getting that error.

**Comment by ArneSaknussemm89** [comment]
Any updates on this?

**Comment by frank06** [comment]
Sorry – on holidays. Should get it fixed on Tuesday!

**Comment by ArneSaknussemm89** [comment]
No need to apologize; just wanted to follow up!

Thanks for making this package and being super responsive!

**Comment by ArneSaknussemm89** [comment]
Just a quick bump to check in!

**Comment by frank06** [comment]
Yep looking at it now :)

**Comment by frank06** [comment]
@ArneSaknussemm89  Tested and tried in another app and seems to work fine. If you'd like to try `0.8.1` and report back that would be great.

**Comment by ArneSaknussemm89** [comment]
Works like a charm!
