### ISSUE TITLE
How to override findAll()?

### ISSUE THREAD

**Issue by ArneSaknussemm89** [flutterdata/flutter_data#106]
So I'm trying to override a remote adapter and adjust how it's grabbing data from a response.

The response from the API is formatted as such:
```
{
  "data": [] # an array of models
}
```

So I tried adding this mixin:
```dart
mixin BooksAdapter on RemoteAdapter<Book> {
  @override
  String get baseUrl => '${dotenv.env['API_URL']!}${'api/$version'}';

  @override
  String get identifierSuffix => 'Id';

  @override
  Future<List<Book>> findAll({
    bool? remote,
    Map<String, dynamic>? params,
    Map<String, String>? headers,
    bool? syncLocal,
    bool Function(Book)? filterLocal,
    OnData<List<Book>>? onSuccess,
    OnDataError<List<Book>>? onError,
  }) async {
    remote ??= true;
    syncLocal ??= false;
    params = await defaultParams & params;
    headers = await defaultHeaders & headers;
    filterLocal ??= (_) => true;

    if (!shouldLoadRemoteAll(remote, params, headers)) {
      final models =
          localAdapter.findAll().where(filterLocal).toImmutableList(); // throws error saying findAll() cannot be used because protected
      models.map((m) => m._initialize(adapters, save: true)); // can't call the private _initialize method
      return models;
    }

    final result = await sendRequest(
      baseUrl.asUri / urlForFindAll(params) & params,
      method: methodForFindAll(params),
      headers: headers,
      requestType: DataRequestType.findAll,
      key: internalType,
      onSuccess: (data) async {
        // just want to change data to data['data']
        final models = data != null ? deserialize(data['data'] as Object).models.where(filterLocal!).toList(growable: false) : <Book>[];
        return onSuccess?.call(models) ?? models;
      },
      onError: onError,
    );
    return result ?? <Book>[];
  }

  @override
  FutureOr<Map<String, String>> get defaultHeaders async => await super.defaultHeaders
    ..addAll({'Accept': 'application/json'});
}
```

I'm guessing there's a different way? The docs show a way to override an `onResponse` function but I don't see that anywhere so I'm assuming that's deprecated/removed?

**Comment by frank06** [comment]
Let me have a look tonight but first thing that comes to mind is calling `super.findAll()` in the override with a custom `onSuccess` argument such as:

```dart
onSuccess: (data) {
  return deserialize(data['data'] as Map<String, dynamic>, init: true).model;
},
```

**Comment by ArneSaknussemm89** [comment]
Unfortunately that still doesn't work as the parent `findAll` method still attempts to convert the data from the API call into a List<T>:
```dart
/// lib/src/repository/remote_adapter.dart:261

    final result = await sendRequest(
      baseUrl.asUri / urlForFindAll(params) & params,
      method: methodForFindAll(params),
      headers: headers,
      requestType: DataRequestType.findAll,
      key: internalType,
      onSuccess: (data) async {
        if (syncLocal!) {
          await localAdapter.clear();
        }
        /// This is the line I need to override
        final models = data != null
            ? deserialize(data as Object)
                .models
                .where(filterLocal!)
                .toImmutableList()
            : <T>[];
        return onSuccess?.call(models) ?? models;
      },
      onError: onError,
    );
```

**Comment by frank06** [comment]
Sorry if I'm missing something – you do not want to return a `List<T>`? 

 If your JSON response data does not adhere to the standard JSON of the adapter can do that by overriding `deserialize`. Could you share what those look like?

**Comment by ArneSaknussemm89** [comment]
How would I create an adapter for serializing/deserializing the JSON?

Right now it seems like the default deserializer expect the JSON from the API to look like:

```
[
  {
    "id": 1,
    "title": "Book 1",
  },
  {
    "id": 2,
    "title": "Book 2",
  },
]
```

but the response actually looks like:
```
{
  "data: [
      {
      "id": 1,
      "title": "Book 1",
    },
    {
      "id": 2,
      "title": "Book 2",
    },
  ],
}
```

So I just need to change the deserializer to try and deserialize the `data` key to get the list of models. If I need to create another adapter, what adapter should my mixin be on and what should I override?

**Comment by frank06** [comment]
I would think something like:

```dart
mixin SomeAdapter<T extends DataModel<T>> on RemoteAdapter<T> {
  @override
  DeserializedData<T, DataModel> deserialize(dynamic data,
      {bool init, String key}) {
    return super.deserialize(data['data'], key: key, init: init);
  }
}
```

You can then mix this into any model that has that JSON structure

**Comment by ArneSaknussemm89** [comment]
That worked like a charm! And now I think I'm starting to understand the adapter better, thanks for the quick replies and help!

**Comment by frank06** [comment]
Glad that it worked!

**Comment by musiolmarco** [comment]
Hello, is there maybe any update on this? Because I am trying to do the same thing with the newest pre release 2.0.0 version (I am not sure if it's also failing in the 1.6.0) and sadly even with overwriting the new parameters, it does not work. ☹️

```dart
mixin MyJSONServerAdapter on Adapter<Album> {
  @override
  String get baseUrl =>
      "https://crudcrud.com/api/533e9b77b7c841879470be0d79e5a5d0/";

  @override
  Future<DeserializedData<Album>> deserialize(
    Object? data, {
    String? key,
    bool async = true,
  }) async {
    if (data is Map && data.containsKey('docs')) {
      return super.deserialize(
        data['docs'],
        key: key,
        async: async,
      );
    }

    return super.deserialize(
      data,
      key: key,
      async: async,
    );
  }
}
```
_(It's the "docs" key here in the JSON data, instead of "data" in the example from @ArneSaknussemm89 )_

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'num' in type cast
#0      _$AlbumFromJson (package:new_flutter_data_example/core/data/models/album.g.dart:49:23)
#1      _$AlbumAdapter.deserializeLocal.<anonymous closure> (package:new_flutter_data_example/core/data/models/album.g.dart:21:39)
#2      _BaseAdapter.internalWrapStopInit (package:flutter_data/src/adapter/adapter.dart:371:17)
#3      _$AlbumAdapter.deserializeLocal (package:new_flutter_data_example/core/data/models/album.g.dart:21:12)
#4      _SerializationAdapter._deserialize (package:flutter_data/src/adapter/serialization_adapter.dart:90:31)
#5      _SerializationAdapter.deserializeAndSave.<anonymous closure> (package:flutter_data/src/adapter/serialization_adapter.dart:118:25)
#6      _BaseAdapter.runInIsolate.<anonymous closure> (package:flutter_data/src/adapter/adapter.dart:210:18)
<asynchronous suspension>
#7      _RemoteRunner._run (dart:isolate:1092:18)
<asynchronous suspe<…>
```
