### ISSUE TITLE
Failing tests due to disposed Provider

### ISSUE THREAD

**Issue by GabrielAraujo** [flutterdata/flutter_data#125]
Hey,

After upgrading to the version 1.0.1 the tests started failing with the following exception: 
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: Tried to read a provider from a ProviderContainer that was already disposed
```

It happens at the end of the test execution when the ref is being disposed and it tries to dispose all `repositoryProviders` referenced at the `_repositoryInitializerProviderFamily` provider generated by flutter data located on the file `main.data.dart`

Do you have a hint of what it might be?

**Comment by frank06** [comment]
@GabrielAraujo can you share a stacktrace?

**Comment by GabrielAraujo** [comment]
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: Tried to read a provider from a ProviderContainer that was already disposed

When the exception was thrown, this was the stack:
#0      ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:455:7)
#1      ProviderElementBase.watch (package:riverpod/src/framework/provider_base.dart:732:32)
#2      _repositoryInitializerProviderFamily.<anonymous closure>.<anonymous closure> (package:spectora_mobile/main.data.dart:103:13)
#3      _runGuarded (package:riverpod/src/framework/container.dart:5:7)
#4      Iterable.forEach (dart:core/iterable.dart:279:35)
#5      ProviderElementBase._runOnDispose (package:riverpod/src/framework/provider_base.dart:909:26)
#6      ProviderElementBase.dispose (package:riverpod/src/framework/provider_base.dart:860:5)
#7      ProviderContainer.dispose (package:riverpod/src/framework/container.dart:660:15)
#8      ProviderScopeState.dispose (package:flutter_riverpod/src/framework.dart:194:15)
#9      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
#10     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
#11     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#12     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
#13     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2879:27)
#14     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2510:15)
#15     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2878:7)
#16     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1159:19)
#17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#20     AutomatedTestWidgetsFlutterBinding.scheduleWarmUpFrame (package:flutter_test/src/binding.dart:1085:5)
#21     runApp (package:flutter/src/widgets/binding.dart:1037:7)
#22     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:824:7)
<asynchronous suspension>

The test description was:
  it should an display error
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by jamesdixon** [comment]
@frank06 happy new year, man! hope all is well! any thoughts on this one?

**Comment by frank06** [comment]
Happy new year @jamesdixon !  I am not sure what it is. The testing utilities are not high priority and I'd need an app using them to debug.
