### ISSUE TITLE
Multiple `watchOne` does not run

### ISSUE THREAD

**Issue by stephane-segning** [flutterdata/flutter_data#143]
I have a list of `chat-item` and I for each item in the list, I use the `watchOne` to get the corresponding `chat`. I wasn't sure at first, but now I do: Only one `watchOne` is called every time the app runs.

Am I doing things right ? Or am I missing something ?

**Comment by stephane-segning** [comment]
This is what I've tried so far:
```dart
typedef FinderWidgetBuilder<T> = Widget Function(
    BuildContext context, T t);

class FileFinder extends HookConsumerWidget {
  final FinderWidgetBuilder<FileBase> builder;
  final WidgetBuilder? onLoad;
  final String id;

  const FileFinder({
    Key? key,
    this.onLoad,
    required this.id,
    required this.builder,
  }) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.files.watchOne(id);
    final data = state.model;
    if (data == null) { // <-- Entered only for the first item of the parent list
      if (onLoad != null) return Builder(builder: onLoad!);
      return const FilePlaceholder();
    }
    return builder(context, data);
  }
}

class FilePlaceholder ...
```

which is resolving the object I'm looking for, but never returning a `model`'s `state` with the new value. So I'm having only the `data == null` part validated. 

So if I use this Widget to render a list of files, I get only the first fetched and observed. All others are `FilePlaceholder`. After some researches, it seems to be related to flutter hooks, and not flutter data.

So I'm getting this error:

```
Error: At least listener of the StateNotifier Instance of '_FunctionalStateNotifier<DataGraphEvent, List<DataGraphEvent>>' threw an exception
when the notifier tried to update its state.

The exceptions thrown are:

Unexpected null value.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63  nullCheck
packages/flutter_data/src/repository/remote_adapter_watch.dart 245:46             <fn>
packages/flutter_data/src/graph/notifier_extension.dart 23:17                     <fn>
packages/state_notifier/state_notifier.dart 225:23                                set state
packages/flutter_data/src/graph/notifier_extension.dart 11:32                     set state
packages/flutter_data/src/graph/notifier_extension.dart 82:17                     <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19           internalCallback



    at Object.throw_ [as throw] (http://localhost:64037/dart_sdk.js:5067:11)
    at _FunctionalStateNotifier.new.set state (http://localhost:64037/packages/state_notifier/state_notifier.dart.lib.js:182:21)
    at _FunctionalStateNotifier.new.set state [as state] (http://localhost:64037/packages/flutter_data/src/graph/notifier_extension.dart.lib.js:42:28)
    at http://localhost:64037/packages/flutter_data/src/graph/notifier_extension.dart.lib.js:141:27
    at internalCallback (http://localhost:64037/dart_sdk.js:26619:11)
```

Does someone know how to solve this?

**Comment by frank06** [comment]
Could you share some code of how you are using watchOne?

**Comment by frank06** [comment]
Oh I see. Let me have a look at this on Monday

**Comment by frank06** [comment]
Would you be able to set a conditional breakpoint at `flutter_data/src/repository/remote_adapter_watch.dart 245:46` and share the stacktrace when `_notifier.data.model` is `null`?

**Comment by stephane-segning** [comment]
I'll come back to you tomorrow with more stacktrace 😁

**Comment by frank06** [comment]
Please do :)

**Comment by frank06** [comment]
Please reopen when you are able to reproduce and share
