### ISSUE TITLE
❌ Adjusting deserialize() method with custom data key is not working

### ISSUE THREAD

**Issue by musiolmarco** [flutterdata/flutter_data#272]
Hello, are there maybe any updates on [this](https://github.com/flutterdata/flutter_data/issues/106)? Because I am trying to do the same thing with the newest pre release 2.0.0 version and sadly even with overwriting the new parameters, it does not work. ☹️ (I am not sure if it's also failing in the 1.6.0)

```dart
mixin MyJSONServerAdapter on Adapter<Album> {
  @override
  String get baseUrl =>
      "https://crudcrud.com/api/533e9b77b7c841879470be0d79e5a5d0/";

  @override
  Future<DeserializedData<Album>> deserialize(
    Object? data, {
    String? key,
    bool async = true,
  }) async {
    if (data is Map && data.containsKey('docs')) {
      return super.deserialize(
        data['docs'],
        key: key,
        async: async,
      );
    }

    return super.deserialize(
      data,
      key: key,
      async: async,
    );
  }
}
```
_(It's the "docs" key here in the JSON data, instead of "data" in the example from @ArneSaknussemm89 )_

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'Null' is not a subtype of type 'num' in type cast
#0      _$AlbumFromJson (package:new_flutter_data_example/core/data/models/album.g.dart:49:23)
#1      _$AlbumAdapter.deserializeLocal.<anonymous closure> (package:new_flutter_data_example/core/data/models/album.g.dart:21:39)
#2      _BaseAdapter.internalWrapStopInit (package:flutter_data/src/adapter/adapter.dart:371:17)
#3      _$AlbumAdapter.deserializeLocal (package:new_flutter_data_example/core/data/models/album.g.dart:21:12)
#4      _SerializationAdapter._deserialize (package:flutter_data/src/adapter/serialization_adapter.dart:90:31)
#5      _SerializationAdapter.deserializeAndSave.<anonymous closure> (package:flutter_data/src/adapter/serialization_adapter.dart:118:25)
#6      _BaseAdapter.runInIsolate.<anonymous closure> (package:flutter_data/src/adapter/adapter.dart:210:18)
<asynchronous suspension>
#7      _RemoteRunner._run (dart:isolate:1092:18)
<asynchronous suspe<…>
```

**Comment by frank06** [comment]
Sorry what exactly is at `album.g.dart:49:23`? Have you debugged?

**Comment by musiolmarco** [comment]
Hey @frank06, thanks for the fast answer. 🙌

I just debugged it again and actually found the error. I had to override the `deserializeAndSave()` method instead of the `deserialize()` method to make it work.

I don't know from which version or which commit this was changed exactly, so the old answer is not working anymore, but I just found out that the code never reached the `deserialize()` method without adjusting the `deserializeAndSave()` method and therefore didn't even log anything when I tried to log something with the `log()` method.

## 👉 Here is the full code that is working now with using `ref.albums.watchAll(remote: true)` in the UI
```dart
import 'package:flutter_data/flutter_data.dart';
import 'package:json_annotation/json_annotation.dart';
import 'dart:developer' as dev;

part 'album.g.dart';

@JsonSerializable()
@DataAdapter([MyJSONServerAdapter])
class Album extends DataModel<Album> {
  @override
  final int id;

  final int userId;
  final String title;
  Album({
    required this.id,
    required this.userId,
    required this.title,
  });
}

mixin MyJSONServerAdapter on Adapter<Album> {
  @override
  String get baseUrl => "http://localhost:8088/api/";

  @override
  Future<DeserializedData<Album>> deserializeAndSave(
    Object? data, {
    String? key,
    bool notify = true,
    bool ignoreReturn = false,
  }) {
    if (data is Map && data.containsKey('docs')) {
      return super.deserializeAndSave(
        data['docs'],
        key: key,
        notify: notify,
        ignoreReturn: ignoreReturn,
      );
    }

    return super.deserializeAndSave(
      data,
      key: key,
      notify: notify,
      ignoreReturn: ignoreReturn,
    );
  }

  // Attempt with old answer (Not working anymore)
  //
  // @override
  // Future<DeserializedData<Album>> deserialize(
  //   Object? data, {
  //   String? key,
  //   bool async = true,
  // }) async {

  //   if (data is Map && data.containsKey('docs')) {
  //     return super.deserialize(
  //       data['docs'],
  //       key: key,
  //       async: async,
  //     );
  //   }

  //   return super.deserialize(
  //     data,
  //     key: key,
  //     async: async,
  //   );
  // }
}

```

**Comment by musiolmarco** [comment]
Just another update on that since I looked at the new code it would be now:

```dart
  @override
  Future<DeserializedData<Album>> deserializeAsync(
    Object? data, {
    String? key,
    bool save = false,
    bool ignoreReturn = false,
    bool notify = true,
  }) async {
    if (data is Map && data.containsKey('docs')) {
      return super.deserializeAsync(
        data['docs'],
        key: key,
        notify: notify,
        ignoreReturn: ignoreReturn,
        save: save,
      );
    }
    return super.deserializeAsync(
      data,
      key: key,
      notify: notify,
      ignoreReturn: ignoreReturn,
      save: save,
    );
  }
```
